k9s:
  cluster: kubernetes
  namespace:
    active: cp-automation-dp
    lockFavorites: false
    favorites:
    - all
    - vbmdp
    - cp1-ns
    - vdp
    - cp-automation-dp
    - msg-qa
    - matt-dp
    - nperf12-my-ns
    - k8dp2
  view:
    active: pods
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
  proxy: null
